import Link from 'next/link';
import { ArrowUpRight, Sparkles } from 'lucide-react';
import { api } from '@/api';
import { ProductCard } from '@/components/product-card';
import { ServiceCard } from '@/components/service-card';

export default async function Home() {
  const [products, services] = await Promise.all([api.getProducts(), api.getServices()]);
  return <main><section style={{background:'linear-gradient(115deg,#1f4a2c,#315f3b 58%,#b9752d)',color:'white',position:'relative',overflow:'hidden'}}><div className="container" style={{minHeight:570,padding:'90px 0 80px',display:'flex',alignItems:'flex-end'}}><div style={{maxWidth:720}}><span className="eyebrow" style={{color:'#f1c98d'}}>Maison de matieres</span><h1 className="display" style={{margin:'22px 0',maxWidth:700}}>Des pieces qui donnent un ton au quotidien.</h1><p style={{maxWidth:500,fontSize:18,lineHeight:1.6,opacity:.88}}>Veneria imagine des interieurs sensibles, entre artisanat mediterraneen et lignes contemporaines.</p><div style={{display:'flex',gap:12,marginTop:30}}><Link href="/produits" style={{background:'#fff',color:'var(--green)',padding:'13px 18px',fontWeight:700}}>Explorer les objets <ArrowUpRight size={16} style={{verticalAlign:'middle'}}/></Link><Link href="/services" style={{border:'1px solid rgba(255,255,255,.5)',padding:'13px 18px'}}>Decouvrir les services</Link></div></div></div><Sparkles size={280} strokeWidth={.5} style={{position:'absolute',right:'5%',top:'15%',opacity:.16}}/></section><section className="container" style={{padding:'90px 0 0'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'end',marginBottom:24}}><div><span className="eyebrow">La selection</span><h2 style={{fontSize:34,marginTop:10}}>Objets en vedette</h2></div><Link href="/produits" style={{color:'var(--green)',fontWeight:700}}>Voir tout <ArrowUpRight size={15} style={{verticalAlign:'middle'}}/></Link></div><div className="grid">{products.map((product)=><ProductCard key={product.id} product={product}/>)}</div></section><section className="container" style={{padding:'90px 0'}}><div style={{marginBottom:24}}><span className="eyebrow">L'accompagnement</span><h2 style={{fontSize:34,marginTop:10}}>Des services avec intention</h2></div><div className="grid">{services.map((service)=><ServiceCard key={service.id} service={service}/>)}</div></section></main>;
}
